version: "3.9"

services:
  web:
    container_name: chasiss
    build:
      dockerfile: Dockerfile
    volumes:
      - '..:/root/'
    networks:
      - app
    ports:
      - 80:80
  server:
    container_name: php
    image: php:fpm-alpine
    volumes:
      - '..:/root/'
    networks:
      - app

networks:
  app:
    name: app